from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

from cramrag.config import get_settings

# Alembic Config object, providing access to the values in alembic.ini.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Migrations are written by hand rather than autogenerated, so there is no
# model metadata to compare against. See db/README.md for the reasoning.
target_metadata = None


def _database_url() -> str:
    """The connection URL, from the same settings the API uses.

    Passed straight to create_engine rather than through
    config.set_main_option, because alembic.ini is parsed by configparser and a
    password containing '%' would be read as an interpolation and corrupted.
    """
    return get_settings().sqlalchemy_url


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it, for review or manual apply."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(_database_url(), poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
